type Corpo = { icon: string; alt: string, className?: string };

export const corpos: Record<string, Corpo> = {
    openai: { icon: "/icons/openai.svg", alt: "OpenAI logo", className: "invert dark:invert-0" },
    anthropic: { icon: "/icons/anthropic.svg", alt: "Anthropic logo" },
    google: { icon: "/icons/google.svg", alt: "Google logo" },
    "z-ai": { icon: "/icons/zai.svg", alt: "ZAI logo", className: "dark:invert" },
    "zai": { icon: "/icons/zai.svg", alt: "ZAI logo", className: "dark:invert" },
    deepseek: { icon: "/icons/deepseek.svg", alt: "DeepSeek logo" },
    qwen: { icon: "/icons/qwen.svg", alt: "Qwen logo" },
    alibaba: { icon: "/icons/qwen.svg", alt: "Alibaba logo" },
    "x-ai": { icon: "/icons/xai.svg", alt: "XAI logo", className: "dark:invert" },
    "spacexai": { icon: "/icons/xai.svg", alt: "SpaceXAI logo", className: "dark:invert" },
    meta: { icon: "/icons/meta.svg", alt: "Meta logo" },
    "meta-llama": { icon: "/icons/meta.svg", alt: "Meta logo" },
    bytedance: { icon: "/icons/bytedance.svg", alt: "Bytedance logo" },
    amazon: { icon: "/icons/amazon.svg", alt: "Amazon logo" },
    mistralai: { icon: "/icons/mistral.svg", alt: "MistralAI logo" },
    mistral: { icon: "/icons/mistral.svg", alt: "MistralAI logo" },
    moonshotai: { icon: "/icons/moonshot.svg", alt: "MoonshotAI logo", className: "dark:invert" },
    tencent: { icon: "/icons/tencent.svg", alt: "Tencent logo" },
    nvidia: { icon: "/icons/nvidia.svg", alt: "NVIDIA logo" },
    xiaomi: { icon: "/icons/xiaomi.svg", alt: "Xiaomi logo", className: "dark:invert" },
    perplexity: { icon: "/icons/perplexity.svg", alt: "Perplex logo" },
    minimax: { icon: "/icons/minimax.svg", alt: "Minimax logo" },
    microsoft: { icon: "/icons/microsoft.svg", alt: "Microsoft logo" },
    nousresearch: { icon: "/icons/nousresearch.svg", alt: "NousResearch logo", className: "dark:invert" },
    poolside: { icon: "/icons/poolside.svg", alt: "Poolside logo" },
};