export type Pic = { icon: string; alt: string, className?: string };

export const pics_corpos: Record<string, Pic> = {
    openai: { icon: "/icons/openai.svg", alt: "OpenAI logo", className: "invert dark:invert-0" },
    anthropic: { icon: "/icons/anthropic.svg", alt: "Anthropic logo" },
    google: { icon: "/icons/google.svg", alt: "Google logo" },
    "z-ai": { icon: "/icons/zai.svg", alt: "ZAI logo", className: "dark:invert" },
    "zai": { icon: "/icons/zai.svg", alt: "ZAI logo", className: "dark:invert" },
    deepseek: { icon: "/icons/deepseek.svg", alt: "DeepSeek logo" },
    qwen: { icon: "/icons/qwen.svg", alt: "Qwen logo" },
    alibaba: { icon: "/icons/qwen.svg", alt: "Alibaba logo" },
    "x-ai": { icon: "/icons/xai.svg", alt: "XAI logo", className: "dark:invert" },
    "spacexai": { icon: "/icons/xai.svg", alt: "SpaceXAI logo", className: "dark:invert" },
    meta: { icon: "/icons/meta.svg", alt: "Meta logo" },
    "meta-llama": { icon: "/icons/meta.svg", alt: "Meta logo" },
    bytedance: { icon: "/icons/bytedance.svg", alt: "Bytedance logo" },
    amazon: { icon: "/icons/amazon.svg", alt: "Amazon logo" },
    mistralai: { icon: "/icons/mistral.svg", alt: "MistralAI logo" },
    mistral: { icon: "/icons/mistral.svg", alt: "MistralAI logo" },
    moonshotai: { icon: "/icons/moonshot.svg", alt: "MoonshotAI logo", className: "dark:invert" },
    tencent: { icon: "/icons/tencent.svg", alt: "Tencent logo" },
    nvidia: { icon: "/icons/nvidia.svg", alt: "NVIDIA logo" },
    xiaomi: { icon: "/icons/xiaomi.svg", alt: "Xiaomi logo", className: "dark:invert" },
    perplexity: { icon: "/icons/perplexity.svg", alt: "Perplex logo" },
    minimax: { icon: "/icons/minimax.svg", alt: "Minimax logo" },
    microsoft: { icon: "/icons/microsoft.svg", alt: "Microsoft logo" },
    nousresearch: { icon: "/icons/nousresearch.svg", alt: "NousResearch logo", className: "dark:invert" },
    poolside: { icon: "/icons/poolside.svg", alt: "Poolside logo" },
};

export const pics_models: Record<string, Pic> = {
    gpt: pics_corpos.openai,
    claude: pics_corpos.anthropic,
    gemini: pics_corpos.google,
    glm: pics_corpos["z-ai"],
    deepseek: pics_corpos.deepseek,
    qwen: pics_corpos.qwen,
    grok: pics_corpos["x-ai"],
    muse: pics_corpos.meta,
    llama: pics_corpos.meta,
    doubao: pics_corpos.bytedance,
    amazon: pics_corpos.amazon,
    nova: pics_corpos.amazon,
    mistral: pics_corpos.mistral,
    ministral: pics_corpos.mistral,
    codestral: pics_corpos.mistral,
    kimi: pics_corpos.moonshotai,
    hy: pics_corpos.tencent,
    hunyuan: pics_corpos.tencent,
    nemotron: pics_corpos.nvidia,
    mimo: pics_corpos.xiaomi,
    sonar: pics_corpos.perplexity,
    minimax: pics_corpos.minimax,
    phi: pics_corpos.microsoft,
    hermes: pics_corpos.nousresearch,
    deephermes: pics_corpos.nousresearch
};

export const pics_endpoints: Record<string, Pic> = {
    "api.openai.com": pics_corpos.openai,
    "api.anthropic.com": pics_corpos.anthropic,
    "generativelanguage.googleapis.com": pics_corpos.google,
    "api.z.ai": pics_corpos["z-ai"],
    "open.bigmodel.cn": pics_corpos["z-ai"],
    "api.deepseek.com": pics_corpos.deepseek,
    "dashscope.aliyuncs.com": pics_corpos.qwen,
    "dashscope-intl.aliyuncs.com": pics_corpos.qwen,
    "dashscope-us.aliyuncs.com": pics_corpos.qwen,
    "api.x.ai": pics_corpos["x-ai"],
    "api.llama.com": pics_corpos.meta,
    "ark.cn-beijing.volces.com": pics_corpos.bytedance,
    "ark.ap-southeast.bytepluses.com": pics_corpos.bytedance,
    "api.mistral.ai": pics_corpos.mistral,
    "codestral.mistral.ai": pics_corpos.mistral,
    "api.moonshot.ai": pics_corpos.moonshotai,
    "api.moonshot.cn": pics_corpos.moonshotai,
    "api.hunyuan.cloud.tencent.com": pics_corpos.tencent,
    "integrate.api.nvidia.com": pics_corpos.nvidia,
    "api.xiaomimimo.com": pics_corpos.xiaomi,
    "token-plan-cn.xiaomimimo.com": pics_corpos.xiaomi,
    "token-plan-sgp.xiaomimimo.com": pics_corpos.xiaomi,
    "token-plan-ams.xiaomimimo.com": pics_corpos.xiaomi,
    "api.perplexity.ai": pics_corpos.perplexity,
    "api.minimax.io": pics_corpos.minimax,
    "api.minimaxi.com": pics_corpos.minimax,
    "models.inference.ai.azure.com": pics_corpos.microsoft,
    "models.github.ai": pics_corpos.microsoft,
    "inference-api.nousresearch.com": pics_corpos.nousresearch,
    "inference.poolside.ai": pics_corpos.poolside,
    "openrouter.ai": { icon: "/icons/openrouter.svg", alt: "OpenRouter logo", className: "dark:invert" },
    "ai-gateway.vercel.sh": { icon: "/icons/vercel.svg", alt: "Vercel logo", className: "dark:invert" },
    "gateway.vercel.ai": { icon: "/icons/vercel.svg", alt: "Vercel logo", className: "dark:invert" },
    "api.typesafe.ai": { icon: "/icons/typesafe.svg", alt: "TypeSafe logo", className: "dark:invert" },
    "gateway.ai.cloudflare.com": { icon: "/icons/cloudflare.svg", alt: "Cloudflare logo"},
    "api.truefoundry.com": { icon: "/icons/truefoundry.svg", alt: "TrueFoundry logo"},
};

export function getPic(model: string, isEndpoint: boolean): Pic | undefined {
    return isEndpoint
        ? pics_models[model.toLowerCase().split(/[-.\d]/)[0]]
        : pics_corpos[model.split("/")[0]];
}
